name: ffw_stack_trace_parser
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'

executables:
  ffw_stack_trace_parser:

dependencies:
  path: ^1.8.0
  source_map_stack_trace: ^2.1.0
  source_maps: ^0.10.10
  args: ^2.3.0
  console: ^4.1.0
  stack_trace: ^1.10.0
  quiver: ^3.0.1+1

dev_dependencies:
  lints: ^1.0.1
